# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d2be84bdb59f14fb5207c9e58a04c9fbe28f9a88712980aeebec9cdb55cc58feaf941953b89cb0ee4329f1862add8688641d6ed29f7b87ef3880fac9186ccb6

test:
  secret_key_base: 9e569dcac4a7cb489a992a16ecca6b5df51ca08a73da5f6005cbc5302f57cbf39e588c7750c75b344ce080154121124f07c306c20d8fcb05e2bc38b8721a7f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
